version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-18-211-48-247.compute-1.amazonaws.com
            port: '5432'
            database: d7qemgdnc9aapt
            ssl: true
            user: ixfvzimzmbcuic
            password: 49e7c9b1ff40d8f2effdd96ac92b21abd9d071498aa18424c5425f9635cc4959
            migrations: true